services:
  postgres:
    ports:
      - ${POSTGRES_PORT}:5432

  rabbitmq:
    ports:
      - 15672:15672
      - ${RABBITMQ_PORT}:5672

  redis:
    ports:
      - ${REDIS_PORT}:6379

  api:
    ports:
      - ${API_PORT}:3000

  hdwallet:
    ports:
      - ${HDWALLET_PORT}:8000