services:
  postgres:
    image: postgres
    restart: always
    command: postgres -c 'max_connections=2000'
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=donation
      - POSTGRES_DB=donation
    networks:
      - db_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
#    environment:
#      - RABBITMQ_DEFAULT_USER=rabbitmq
#      - RABBITMQ_DEFAULT_PASS=rabbitmq
#      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 15672:15672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    networks:
      - rabbitmq_network

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
#    volumes:
#      - ./data/redis:/bitnami/redis/data
    networks:
      - redis_network

  api:
    build:
      context: api
    env_file:
      - .env
      - api/.env
    networks:
      - db_network
      - rabbitmq_network
      - hdwallet_network
    depends_on:
      - postgres
      - rabbitmq

  collector:
    build:
      context: collector
    env_file:
      - .env
      - collector/.env
    networks:
      - rabbitmq_network
      - redis_network
    depends_on:
      - rabbitmq
      - redis

  hdwallet:
    build:
      context: hdwallet
    networks:
      - hdwallet_network

networks:
  db_network:
    driver: bridge
  rabbitmq_network:
    driver: bridge
  redis_network:
    driver: bridge
  hdwallet_network:
    driver: bridge