services:
  postgres:
    image: postgres
    restart: always
    command: postgres -c 'max_connections=2000'
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=donation
      - POSTGRES_DB=donation
    networks:
      - db_network

  api:
    build:
      context: api
    env_file:
      - .env
      - api/.env
    ports:
      - 3001:3000
    networks:
      - db_network
    depends_on:
      - postgres

networks:
  db_network:
    driver: bridge