CREATE TABLE transactions (
    id VARCHAR(100) PRIMARY KEY,
    amount DECIMAL(18, 6) NOT NULL,
    address VARCHAR(100) NOT NULL,
    type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);